# example values
server:
  port: 8080

spring:
  datasource:
    db_name: search_engine
    host: jdbc:mysql://localhost:3306

    username: root
    password: 198855
    url: ${spring.datasource.host}/${spring.datasource.db_name}?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=yes
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: http://cimus.biz
      name: cimuz
    - url: http://playback.ru
      name: playback
    - url: https://dimonvideo.ru
      name: dimonvideo
    - url: https://dombulgakova.ru
      name: dombulgakova
  name: SearchBotFix/2.0
  referer: https://google.com
  timeout: 15000
  contentType: text/html; charset=utf-8

search-settings:
  limit: 20
  offset: 0